### ISSUE TITLE
Can't seem to change the url for the client

### ISSUE THREAD

**Issue by bashilbers** [alexandresalome/mailcatcher#16]
I have the following behat.yml file:

```
default:
    suites:
        default:
            paths: [%paths.base%/features/]
            contexts:
                - FeatureContext
                - Behat\MinkExtension\Context\MinkContext
                - Alex\MailCatcher\Behat\MailCatcherContext

    extensions:
        Behat\MinkExtension:
            base_url: "http://login.dev"
            sessions:
                default:
                    goutte: ~

                javascript:
                    selenium2: ~

        Alex\MailCatcher\Behat\MailCatcherExtension\Extension:
            url: http://login.dev:1080
            purge_before_scenario: true
```

I'm requiring behat 3 and your extension:

```
    "require-dev": {
        "behat/behat": "3.0.*",
        "behat/mink-extension": "2.0.*",
        "behat/mink-goutte-driver": "1.1.*",
        "behat/mink-selenium2-driver": "1.2.*",
        "alexandresalome/mailcatcher": "1.0.*"
    }
```

Debugging the mailcatcher context in my own featurecontext file results in a Client with "http://localhost:1080" as url, which is the default value.

Changing "self::MAILCATCHER_ID" to "behat.mailcatcher.client" on line 54 in Extension.php resolved the issue for me, but I have not enough knowledge about your package for me to feel confident about creating a PR.

What is going wrong in my setup? Is my hardcoded fix actually desired?
