### ISSUE TITLE
Laravel 5: BindingResolutionException (ExceptionHandler) when using MailCatcherContext

### ISSUE THREAD

**Issue by rask** [alexandresalome/mailcatcher#24]
I'm creating Behat tests for a Laravel 5.2 project using Behat 3+, Laravel-Behat-Extension and this package.

My `behat.yml` is as such:

```yaml
default:
    autoload:
        - %paths.base%/tests/Behat/Features/Bootstrap/
    suites:
        default:
            paths: [ %paths.base%/tests/Behat/Features ]
            contexts:
                - App\Tests\Behat\Features\Bootstrap\FeatureContext
                - Behat\MinkExtension\Context\MinkContext
                - Alex\MailCatcher\Behat\MailCatcherContext
    extensions:
        Laracasts\Behat: ~
        Behat\MinkExtension:
            default_session: laravel
            laravel: ~
        Alex\MailCatcher\Behat\MailCatcherExtension\Extension:
            url: http://127.0.0.1:1080
            purge_before_scenario: true
```

When I run

    $ vendor/bin/behat

The feature tests "run", but at the end of a scenario I get this:

```
PHP Fatal Error: Uncaught Illuminate\Contracts\Container\BindingResolutionException:
  Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable.
    in /var/www/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:748
  Stack trace:
    ...
```

When I comment out the MailCatcherContext in `behat.yml` my suite works normally:

```yml
...
    contexts:
        - App\Tests\Behat\Features\Bootstrap\FeatureContext
        - Behat\MinkExtension\Context\MinkContext
        #- Alex\MailCatcher\Behat\MailCatcherContext
...
```

The MailCatcherContext is loading OK, as `$ vendor/bin/behat -dl` displays things like

```
...
default | When /^I purge mails$/
default | When /^I open mail from "([^"]+)"$/
...
```

Has this package been tested with Behat 3 and Laravel 5? Any tips on how to debug this and see whether the issue lives inside this package or Laravel?
